name: Build, check and publish

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # TODO: take from go.mod
          go-version: 1.22.5
      - name: Install dependencies
        run: go get .
      - name: Lint
        run: go vet
      - name: Test unit
        run: make test-unit
      # Build images before running local tests to exploit cache
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build and load lambda Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./assets"
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and load reverse proxy Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Test e2e as local proxy
        run: make test-local
      # TODO
      # - name: Test e2e as AWS proxy
      #   run: make test-aws
      - name: Debug
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"

  release:
    runs-on: ubuntu-latest
    needs: check
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          short-description: |
            HTTP reverse proxy for lambda functions. Use lambdas as if they were
            HTTP services both locally and on AWS.
