name: Build, check and publish

on:
  push:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # TODO: take from go.mod
          go-version: 1.22.5
      - name: Install dependencies
        run: go get .
      - name: Lint
        run: go vet
      - name: Test unit
        run: make test-unit
      # Build image before running local e2e to exploit cache
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build and load lambda Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./assets"
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and load reverse proxy Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Test e2e as local proxy
        run: make test-local
      # TODO
      # - name: Test e2e as AWS proxy
      #   run: make test-aws

  # TODO: only if the current branch is tagged?
  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: gabrielelana/lambda-reverse-proxy:latest
